### ISSUE TITLE
Fix language base-file and regenerate the .pot

### ISSUE THREAD

**Issue by EugenioPetulla** [CodeAtCode/AdRotate-Extra-Settings#1]
Lucrezia Argentino translated this in other languages and she find some English errors in the code. She provided an en_EN language file in order to fix the problem but you should put the fix directly in the code and regenerate the POT after.

Plus: update the plugin on WordPress repo!

**Comment by Mte90** [comment]
ok I wait the po file :-)

**Comment by EugenioPetulla** [comment]
check my last commit man! ;P

63061eec722ca744eb9ed27994b54a3675138162
