### ISSUE TITLE
Suggestion: On the AdRotate widget, place a list of Ad names instead of requiring to type an ID

### ISSUE THREAD

**Issue by GwynethLlewelyn** [CodeAtCode/AdRotate-Extra-Settings#2]
Hi!

It seems that you're asking for requests, so here is mine :)

On the AdRotate widget, you have to explicitly type the ID number of the Ad you wish to show. Now this means having two windows (or tabs) open, one to configure the widget, another to get a list of Ad IDs so you know which one to place.

Other plugins just add a selection box with the Ad names. It's much easier and more user-friendly, while at the same time preventing that 'wrong' ads are shown because you mistyped a number. To make it even better, only active/valid ads ought to be shown — that way, if you don't see the ad name you expect, you _know_ that something is wrong with it. Just putting a number is a shot in the dark — it might work (if you put it the correct one!), or it might not.

I have no idea if AdRotate is planning that enhancement, but, if they aren't, you've got a chance to show you can do better than them :)

Thanks!

**Comment by Mte90** [comment]
Uhm interesting idea I have to see if there are hooks for it :-)

**Comment by Mte90** [comment]
This plugin doesn't add stuff from a php side but only javascript and is not possible to have this list of id inside the widget unluckly.
